version: '3'
volumes:
  persistent:


services:
  upload-node:
    build: .
    restart: on-failure:5
    volumes:
      - ${UPLOADS_PATH:?Path on the disk where to store ready recordings}:/app/uploads:rw
      - persistent:/persistent:rw
    ports:
      - "43325:8123"
